version: '3'
services:
  api-1:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-2:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-3:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-4:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-5:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-6:
    image: "hello-api:alpha"
    ports:
      - "9000"
  envoy-proxy:
    image: "envoyproxy/envoy:v1.13.1"
    ports:
      - "80:80"
    volumes:
      - ./proxy-static-bootstrap.yaml:/etc/envoy/envoy.yaml
