version: '3'
services:
  api-1:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-2:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-3:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-4:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-5:
    image: "hello-api:alpha"
    ports:
      - "9000"
  api-6:
    image: "hello-api:alpha"
    ports:
      - "9000"
  envoy-proxy:
    image: "envoyproxy/envoy:v1.13.1"
    ports:
      - "80:80"
      - "9901:9901"
    volumes:
      - ./proxy-static-bootstrap.yaml:/etc/envoy/envoy.yaml
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/envoy-datasource.yaml:/etc/grafana/provisioning/datasources/envoy.yaml
      - ./grafana/dashboard-providers.yaml:/etc/grafana/provisioning/dashboards/providers.yaml
      - ./grafana/envoy-clusters-dashboard.json:/usr/share/grafana/dashboards/envoy-clusters.json
      - ./grafana/envoy-global-dashboard.json:/usr/share/grafana/dashboards/envoy-global.json
